# Generated by Django 3.1.6 on 2021-05-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210522_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bannerslide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='banner')),
            ],
        ),
    ]
