# Generated by Django 3.1.6 on 2021-05-23 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_bannerslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('district', models.CharField(choices=[('Chittagong', 'SATAKNIA'), ('Chittagong', 'ANOWARA'), ('Chittagong', 'BOALKHALI'), ('Chittagong', 'CHANDANAISH'), ('Chittagong', 'HATHAZARI'), ('Chittagong', 'MIRSHARAI'), ('Chittagong', 'PATIYA'), ('Chittagong', 'RANGUNIA'), ('Chittagong', 'SANDWIP'), ('Chittagong', 'BOALKHAL')], max_length=50)),
                ('city', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
