# Generated by Django 3.1.6 on 2021-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210523_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('C', 'Chittagong'), ('D', 'Dhaka'), ('Co', 'Comilla'), ('Ch', 'Chandpur'), ('S', 'Sylhet'), ('C', 'Coxs bazer'), ('B', 'Bandarban')], max_length=200),
        ),
    ]
