# Generated by Django 3.1.6 on 2021-05-24 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210523_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_title', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=200)),
                ('food_price', models.IntegerField()),
                ('dicount_price', models.IntegerField()),
                ('category', models.CharField(choices=[('P', 'Paratha'), ('KB', 'Kachchi Biryani'), ('BK', 'Bhuna Khichuri'), ('PK', 'Patla Khichuri'), ('MP', 'Morog Polao'), ('RC', 'Rice with Curry and vaji'), ('GC', 'Grilled Chicken'), ('H', 'Haleem'), ('SK', 'Sheek Kabab'), ('PO', 'Fuchka'), ('MD', 'Misti Doi'), ('DC', 'Doi Chira'), ('FD', 'Falooda'), ('RM', 'Rasmali'), ('BH', 'Borhani'), ('SL', 'Sweet Lassi')], max_length=2)),
                ('food_image', models.ImageField(upload_to='Food_image')),
                ('restaurent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
