# Generated by Django 3.1.6 on 2021-06-02 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20210524_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resfood',
            name='category',
            field=models.CharField(choices=[('P', 'Paratha'), ('KB', 'Kachchi Biryani'), ('BK', 'Bhuna Khichuri'), ('MP', 'Morog Polao'), ('RC', 'Rice with Curry and vaji'), ('GC', 'Grilled Chicken'), ('H', 'Haleem'), ('SK', 'Sheek Kabab'), ('PO', 'Fuchka'), ('MD', 'Misti Doi'), ('DC', 'Doi Chira'), ('FD', 'Falooda'), ('RM', 'Rasmali'), ('BH', 'Borhani'), ('SL', 'Sweet Lassi')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
