# Generated by Django 3.1.6 on 2021-06-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210602_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='food',
        ),
    ]
