# Generated by Django 3.1.6 on 2021-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(max_length=100)),
                ('Bangli_word', models.CharField(max_length=200)),
                ('Arobi_word', models.CharField(max_length=200)),
            ],
        ),
    ]
